// User Settings
export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const ASSIGN_DEFAULT_SETTINGS = "ASSIGN_DEFAULT_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const REMOVE_USER_SETTINGS = "REMOVE_USER_SETTINGS";
