export const LOAD_POSTS = 'LOAD_POST';
export const LOAD_EDIT_POST = 'LOAD_EDIT_POST';
export const LOAD_USER_POSTS = 'LOAD_USER_POSTS';

export const CREATE_POST = 'CREATE_POST';
export const REMOVE_USER_POST = 'REMOVE_USER_POST';
export const REMOVE_USER_POSTS = 'REMOVE_USER_POSTS';
export const LOAD_USER_BOOKMARKS = 'LOAD_USER_BOOKMARKS';
export const REMOVE_USER_BOOKMARKS = 'REMOVE_USER_BOOKMARKS';

// User Settings
export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const ASSIGN_DEFAULT_SETTINGS = "ASSIGN_DEFAULT_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const REMOVE_USER_SETTINGS = "REMOVE_USER_SETTINGS";
