export const EDIT_POST_LOAD_START   = 'EDIT_POST_LOAD_START';
export const EDIT_POST_LOAD_ERROR   = 'EDIT_POST_LOAD_ERROR';
export const EDIT_POST_LOAD_SUCCESS = 'EDIT_POST_LOAD_SUCCESS';
export const EDIT_POST_CLEAR_ALL    = 'EDIT_POST_CLEAR_ALL';
