export const LOAD_CURRENT_POST = "LOAD_CURRENT_POST";
export const LOAD_CURRENT_POST_COMMENTS = "LOAD_CURRENT_POST_COMMENTS";
export const REMOVE_CURRENT_POST = "REMOVE_CURRENT_POST";
export const INCREMENT_TOTAL_LIKES = "INCREMENT_TOTAL_LIKES";
export const DECREMENT_TOTAL_LIKES = "DECREMENT_TOTAL_LIKES";
